### ISSUE TITLE
Request for Appendix of the Published Paper

### ISSUE THREAD

**Issue by DouDinstein** [successhaha/FDMatch#3]
Hello,
I am reading your paper "Feature Distribution Matching by Optimal Transport for Effective and Robust Coreset Selection". However, I noticed that the paper does not provide the appendix, which has been mentioned in the paper.

I kindly ask if you could consider sharing the appendix or any supplementary materials that might be available. It would be highly appreciated by not only me but also by other researchers in the community who might be interested in your work.

**Comment by successhaha** [comment]
Hello, thank you very much for your interest in our work. You can give me your email address and I will send the supplementary materials to you.

**Comment by DouDinstein** [comment]
Thank you very much for considering my request. My email address is lililalii@qq.com.

**Comment by successhaha** [comment]
Hello, I have sent the supplementary materials to your email. If this study is useful to you, please give me a star. Thank you!

**Comment by DouDinstein** [comment]
Hi, I have received the supplementary materials you provided for your paper, and I have starred your GitHub repository.  Thank you once again for your support. Have a good day!
